// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Olbrasoft.Travel.Data.Entity.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SpatialIndexToRegionsOnCoordinates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SpatialIndexToRegionsOnCoordinates));
        
        string IMigrationMetadata.Id
        {
            get { return "201803241938021_SpatialIndexToRegionsOnCoordinates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
